# fly.toml app configuration file generated for black-river-1708 on 2023-09-02T21:34:24-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "black-river-1708"

primary_region = "yul"




[experimental]
allowed_public_ports = []
auto_rollback = true


[build]
    [build.args]
        NODE_VERSION = "16.20.2"

[deploy]
    release_command = "npm run build"


[processes]
    app = "node app.js"




[[services]]
    internal_port = 8080
    processes = ["app"]
    protocol = "tcp"
    auto_stop_machines = true
    auto_start_machines = true
    min_machines_running = 0

[[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

[[services.ports]]
    handlers = ["tls", "http"]
    port = 443


[[services.tcp_checks]]
    grace_period = "10s"
    interval = "15s"
    restart_limit = 0
    timeout = "10s"
    processes = ["app"]

[[services.http_checks]]
    interval = 10000
    grace_period = "5s"
    method = "get"
    path = "/"
    protocol = "http"
    timeout = 2000
    tls_skip_verify = false

[[services.http_service]]
    internal_port = 8080
    force_https = true
    processes = ["app"]





